# Generated by Django 6.1.1 on 2026-09-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='stu_class',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
