# Generated by Django 6.1.1 on 2026-09-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prfiles',
            new_name='Profile',
        ),
    ]
