# Generated by Django 6.1.1 on 2026-09-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('fees', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name': 'TransportDetail',
                'verbose_name_plural': 'TransportDetails',
            },
        ),
    ]
